Repository Representable/representable, pull requests merged in 2020-07, with the labels that each got.

#264 Entry_Test
  main/test_entry.py
Labels: entry-page

#274 fix geojson export crs + right-hand rule
  main/views/main.py
  requirements.txt
Labels: bug

#296 Privacy and Tracking Consent Banner
  main/static/main/css/style.css
  main/static/main/js/main.js
  main/static/main/js/mixpanel.js
  main/templates/main/dashboard/index.html
  main/templates/main/pages/privacy.html
  representable/templates/base.html
Labels: analytics
